apiVersion: v1
kind: Service
metadata:
  labels:
    app: aardvark
  name: aardvark-svc
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
      app: aardvark
  type: ClusterIP
